# hisat2.sub
#
# Specify the HTCondor Universe (vanilla is the default and is used
#  for almost all jobs), the desired name of the HTCondor log file,
#  and the desired name of the standard error file.  
#  Wherever you see $(Cluster), HTCondor will insert the queue number
#  assigned to this set of jobs at the time of submission.
universe = vanilla
log = hisat2-htseq_$(Cluster).log
error = hisat2-htseq_$(Cluster).err
output = hisat2-htseq_$(cluster).out
#
# Specify your executable (single binary or a script that runs several
#  commands), arguments, and a files for HTCondor to store standard
#  output (or "screen output").
#  $(Process) will be a integer number for each job, starting with "0"
#  and increasing for the relevant number of jobs.
executable = hisat2-htseq.sh
arguments = $(infilepath1) $(infilepath2) $(infilepath3) $(infilepath4) $(infilepath5) $(infilepath6) $(infilepath7)
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs. The last of these lines *would* be
#  used if there were any other files needed for the executable to run.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = hisat2-2.2.1-Linux_x86_64.zip,samtools-1.15.1.tar.bz2,http://proxy.chtc.wisc.edu/SQUID/chtc/python37.tar.gz,packages2.tar.gz,Jascendensv1.1.gene.gff3
# +IsBuildJob = true
requirements = (HasCHTCStaging == true) && (HasChtcSoftware == true) && (OpSysMajorVer =?= 7)
#
# Tell HTCondor what amount of compute resources
# each job will need on the computer where it runs.
request_cpus = 4
request_memory = 60GB
request_disk = 100GB
#+LongJob = true
#
# Tell HTCondor to loop through list to run each file as separate job:
queue infilepath1,infilepath2,infilepath3,infilepath4,infilepath5,infilepath6,infilepath7 from hisat2-htseq_filelist.csv
